# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-Coords
version:      0.10
version_from: 
installdirs:  site
requires:
    Astro::SLA:                    0.95
    Astro::Telescope:              0.50
    DateTime:                      0
    Scalar::Util:                  1.13
    Test::More:                    0
    Time::Piece:                   1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
